---
   
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install node dependencies
      shell: |
        cd ~
        curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
        nano /tmp/nodesource_setup.sh
        sudo bash /tmp/nodesource_setup.sh
        
    - name: Install required packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nodejs
        - npm
        - unzip

   
    - name: Install pm2
      npm:
        name: pm2
        global: yes
         
    - name: Install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

    - name: Download deployment package from S3
      shell: |
          rm -rf ~/artifact.zip
          aws s3 cp s3://krishna-s3-bucket9/artifact/artifact.zip ~/.
    
    - name: Unzip deployment package
      shell: |
          unzip /home/ubuntu/artifact.zip -d /home/ubuntu/

    - name: Install backend dependencies
      shell: |
        cd /home/ubuntu/backend
        npm i
  

    - name: Install frontednndependencies
      shell: |
        cd /home/ubuntu/frontend
        npm i
  
    - name: Start backend server
      shell: |
        cd /home/ubuntu/backend
        pm2 start "npm start" --name "backend_postportal"

    - name: Start frontend server
      shell: |
        cd /home/ubuntu/backend
        pm2 start "npm start" --name "frontend_postportal"
   

    