---
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nodejs
        - npm
        # - nodejs
        - awscli
        - unzip

    - name: Install NVM
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        source ~/.bashrc
        nvm install --lts
        nvm use --lts

        
    - name: Install pm2
      npm:
        name: pm2
        global: yes
         
    - name: Install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

    - name: Download deployment package from S3
      shell: |
          rm -rf ~/artifact.zip
          aws s3 cp s3://krishna-s3-bucket9/artifact/artifact.zip ~/.
    
    - name: Unzip deployment package
      shell: |
          sudo apt install unzip -y
          unzip /home/ubuntu/artifact.zip -d /home/ubuntu/

    - name: Install backend dependencies
      shell: |
        cd /home/ubuntu/backend
        npm i
        npm install

    - name: Install frontednndependencies
      shell: |
        cd /home/ubuntu/frontend
        npm i
        npm install
    - name: Start backend server
      shell: |
        cd /home/ubuntu/backend
        pm2 start "npm start" --name "backend_postportal"

    - name: Start frontend server
      shell: |
        cd /home/ubuntu/backend
        pm2 start "npm start" --name "frontend_postportal"
   

    