---
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install node dependencies
      shell: |
        cd ~
        curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
        nano /tmp/nodesource_setup.sh
        sudo bash /tmp/nodesource_setup.sh
        
    - name: Install NodeJS
      apt:
        name: nodejs
        state: present   

    - name: Install unzip
      apt:
        name: unzip
        state: present 
   
    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: Install AWS CLI
      become: true
      shell: snap install aws-cli --classic

    - name: Clean all pm2 processes
      become: true
      shell: |
        pm2 delete all || true

    - name: Cleanup artifact.zip and directories
      shell: |
        rm -f /home/ubuntu/artifact.zip
        rm -rf /home/ubuntu/frontend
        rm -rf /home/ubuntu/backend  

    - name: Download deployment package from S3
      shell: |
          aws s3 cp s3://krishna-s3-bucket9/artifact/artifact.zip /home/ubuntu/
    
    - name: Unzip deployment package
      shell: |
          unzip /home/ubuntu/artifact.zip -d /home/ubuntu/

    - name: Install backend dependencies
      shell: |
        cd /home/ubuntu/backend
        npm i

    - name: Install fronted dependencies
      shell: |
        cd /home/ubuntu/frontend
        npm i
  
    - name: Start backend server
      shell: |
        cd /home/ubuntu/backend
        pm2 start "npm start" --name "backend_postportal"

    - name: Start frontend server
      shell: |
        cd /home/ubuntu/frontend
        pm2 start "npm start" --name "frontend_postportal"
   